name: w_service
version: 0.0.0
dependencies:
  fluri: '>=1.0.0 <2.0.0'
  w_transport:
    git:
      url: git+ssh://git@github.com/Workiva/w_transport.git
      ref: data-validate
#  w_transport: '>=1.0.0 <2.0.0'
dev_dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  coverage:
    git:
      url: https://github.com/ekweible/coverage.git
      ref: 796a265
  dart_codecov_generator:
    git:
      url: https://github.com/ekweible/dart_codecov_generator.git
      ref: 0.3.0
  dart_style: '>=0.1.8 <0.2.0'
  mockito: '>=0.10.0 <0.11.0'
  react: '>=0.7.0 <0.8.0'
  test: '>=0.12.0 <0.12.3'