name: w_service
version: 1.0.0
description: Platform agnostic library for sending and receiving data messages between an application and a server with the ability to shape traffic and transform data through the use of message interceptors.
authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>
homepage: https://github.com/Workiva/w_service
dependencies:
  fluri: "^1.0.1"
  w_transport: "^1.0.1"
dev_dependencies:
  browser: "^0.10.0+2"
  dart_style: "^0.1.8"
  mockito: "^0.10.0"
  react: "^0.7.0"
  test: "^0.12.3+2"
